"""
backend/scripts/seed_knowledge.py
---------------------------------
Chunks every backend/data/knowledge/*.txt, embeds each chunk with Supabase's
built-in `gte-small` model (via the `embed` edge function), and (re)populates
the `knowledge_chunks` pgvector table.

Run once after editing the knowledge corpus:

    SUPABASE_URL=https://<ref>.supabase.co \
    SUPABASE_ANON_KEY=<anon jwt> \
    python backend/scripts/seed_knowledge.py

The table has no write policy, so a temporary `anon` insert/delete policy must
exist while this runs:

    create policy _seed_write on knowledge_chunks for all to anon
      using (true) with check (true);
    -- run this script --
    drop policy _seed_write on knowledge_chunks;

Pass --sql-only to instead write supabase/seed/60_knowledge_chunks.sql (apply it
yourself) and skip the API calls.
"""
import os
import sys
import json
import glob
import urllib.request
import urllib.error
from pathlib import Path

_BACKEND = Path(__file__).resolve().parent.parent
KNOWLEDGE_DIR = _BACKEND / "data" / "knowledge"
OUT_SQL = _BACKEND.parent / "supabase" / "seed" / "60_knowledge_chunks.sql"

TARGET_CHARS = 900
MIN_CHARS = 200


def load_env() -> tuple[str, str]:
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_ANON_KEY")
    if not (url and key):
        for name in (".env.local", ".env"):
            p = _BACKEND / name
            if not p.exists():
                continue
            for line in p.read_text().splitlines():
                line = line.strip()
                if line.startswith("SUPABASE_URL=") and not url:
                    url = line.split("=", 1)[1].strip().strip('"')
                if line.startswith("SUPABASE_ANON_KEY=") and not key:
                    key = line.split("=", 1)[1].strip().strip('"')
    if not (url and key):
        sys.exit("Set SUPABASE_URL and SUPABASE_ANON_KEY (env or backend/.env.local).")
    return url.rstrip("/"), key


def chunk(text: str) -> list[str]:
    """Paragraph-aware: split on blank lines, then greedily merge to ~TARGET_CHARS."""
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks: list[str] = []
    buf = ""
    for para in paras:
        if not buf:
            buf = para
        elif len(buf) + 2 + len(para) <= TARGET_CHARS:
            buf += "\n\n" + para
        else:
            chunks.append(buf)
            buf = para
    if buf:
        if chunks and len(buf) < MIN_CHARS:
            chunks[-1] += "\n\n" + buf
        else:
            chunks.append(buf)
    return chunks


def _post(url: str, headers: dict, body) -> bytes:
    req = urllib.request.Request(url, data=json.dumps(body).encode(), headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def embed(url: str, key: str, text: str) -> list[float]:
    out = _post(
        f"{url}/functions/v1/embed",
        {"Content-Type": "application/json", "Authorization": f"Bearer {key}"},
        {"input": text},
    )
    return json.loads(out)["embedding"]


def build_rows(url: str, key: str) -> list[dict]:
    files = sorted(glob.glob(str(KNOWLEDGE_DIR / "*.txt")))
    if not files:
        sys.exit(f"No .txt files in {KNOWLEDGE_DIR}")
    rows: list[dict] = []
    for path in files:
        name = Path(path).name
        for c in chunk(Path(path).read_text(encoding="utf-8")):
            print(f"  embedding {name}  ({len(c)} chars)", file=sys.stderr)
            rows.append({"source_file": name, "content": c, "embedding": embed(url, key, c)})
    print(f"\n{len(rows)} chunks from {len(files)} files", file=sys.stderr)
    return rows


def write_sql(rows: list[dict]) -> None:
    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    with OUT_SQL.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by backend/scripts/seed_knowledge.py — do not edit by hand.\n")
        f.write("-- Repopulates knowledge_chunks (migrations/20260908_01_knowledge_rag.sql).\n\n")
        f.write("truncate knowledge_chunks;\n\n")
        for r in rows:
            vec = "[" + ",".join(f"{x:.6f}" for x in r["embedding"]) + "]"
            f.write(
                "insert into knowledge_chunks (source_file, content, embedding) values ("
                f"$kc${r['source_file']}$kc$, $kc${r['content']}$kc$, '{vec}');\n"
            )
    print(f"wrote {OUT_SQL}", file=sys.stderr)


def push(url: str, key: str, rows: list[dict]) -> None:
    rest = f"{url}/rest/v1/knowledge_chunks"
    hdr = {"Content-Type": "application/json", "apikey": key, "Authorization": f"Bearer {key}"}
    # wipe existing rows for these source files
    files = sorted({r["source_file"] for r in rows})
    q = ",".join(f'"{f}"' for f in files)
    req = urllib.request.Request(
        f"{rest}?source_file=in.({q})", headers={**hdr, "Prefer": "return=minimal"}, method="DELETE"
    )
    try:
        urllib.request.urlopen(req, timeout=30)
    except urllib.error.HTTPError as e:
        sys.exit(f"DELETE failed ({e.code}) — is the temporary _seed_write policy in place?\n{e.read().decode()}")
    for i in range(0, len(rows), 20):
        _post(rest, {**hdr, "Prefer": "return=minimal"}, rows[i:i + 20])
        print(f"  inserted {min(i + 20, len(rows))}/{len(rows)}", file=sys.stderr)
    print("done", file=sys.stderr)


def main() -> None:
    url, key = load_env()
    rows = build_rows(url, key)
    write_sql(rows)  # always keep the repo artifact fresh
    if "--sql-only" not in sys.argv:
        push(url, key, rows)


if __name__ == "__main__":
    main()
