import app.ssl_patch  # noqa: F401 — must be first; patches SSL before HuggingFace imports
import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Optional
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from app.agent import run_agent

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Build the RAG index on first startup if storage doesn't exist yet.
    Runs in a thread so the synchronous HF model download doesn't block the event loop."""
    try:
        from app.rag import ensure_index_built
        await asyncio.to_thread(ensure_index_built)
    except Exception as e:
        logger.warning(
            "RAG index build failed at startup (will retry on first request): %s", e
        )
    yield  # server runs here


app = FastAPI(
    title="TerraLearn Environmental Agent API",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://localhost:4173",
        "*",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class CropContext(BaseModel):
    crop: str
    plantingDate: str
    yieldEstimate: float
    viabilityScore: float
    profit: float

class AskRequest(BaseModel):
    question: str
    lat: float
    lng: float
    cropContext: Optional[CropContext] = None

class AskResponse(BaseModel):
    answer: str

class RiskBriefRequest(BaseModel):
    lat: float
    lng: float
    crop: str
    plantingDate: str
    yieldEstimate: float
    viabilityScore: float
    profit: float

class RiskBriefResponse(BaseModel):
    brief: str

@app.get("/")
def read_root():
    return {"status": "online", "service": "TerraLearn FastAPI Backend"}

@app.post("/api/ask", response_model=AskResponse)
async def ask_question(req: AskRequest):
    try:
        formatted_input = (
            f"User Question: {req.question}\n"
            f"Target Location Coordinates: Latitude {req.lat}, Longitude {req.lng}"
        )
        if req.cropContext:
            formatted_input += (
                f"\nPre-computed Frontend Crop Result:\n"
                f"- Crop Type: {req.cropContext.crop}\n"
                f"- Planting Date: {req.cropContext.plantingDate}\n"
                f"- Yield Estimate: {req.cropContext.yieldEstimate} tons/ha\n"
                f"- Viability Score: {req.cropContext.viabilityScore}/100\n"
                f"- Calculated Profit: ${req.cropContext.profit:,.2f}"
            )

        answer_text = run_agent(formatted_input)
        if not answer_text:
            answer_text = "No response generated by the environmental agent."

        return AskResponse(answer=answer_text)
    except Exception as e:
        err_str = str(e)
        if "api_key" in err_str.lower() or "401" in err_str or "dummy-key" in err_str or "authentication" in err_str.lower():
            return AskResponse(
                answer="OpenAI API key is missing or invalid. Please configure OPENAI_API_KEY in backend/.env to query the AI agent."
            )
        return AskResponse(answer=f"Error running environmental assistant: {err_str}")


@app.post("/api/risk-brief", response_model=RiskBriefResponse)
async def get_risk_brief(req: RiskBriefRequest):
    """Generate a concise 2-3 sentence environmental risk brief for a crop/location.
    Reuses the existing run_agent — no separate Groq/OpenRouter config created."""
    try:
        internal_prompt = (
            f"You are generating a concise environmental risk brief for a farmer's decision.\n"
            f"Location: Latitude {req.lat}, Longitude {req.lng}\n"
            f"Crop: {req.crop}\n"
            f"Planting Date: {req.plantingDate}\n"
            f"Pre-computed Viability Score: {req.viabilityScore}/100\n"
            f"Estimated Yield: {req.yieldEstimate:.2f} tons/ha\n\n"
            f"Task: Use your available tools (real-time AQI data and environmental knowledge base) "
            f"to write exactly 2-3 sentences summarising the key environmental risks or favourable "
            f"conditions for growing {req.crop} at this location right now. "
            f"Be specific: mention pollutant levels, temperature suitability, or weather risks if relevant. "
            f"Keep it farmer-friendly and actionable. Do not use bullet points."
        )
        brief_text = await asyncio.to_thread(run_agent, internal_prompt)
        # Strip provider footnotes and error prefixes from the brief
        if not brief_text or brief_text.startswith("Error") or "rate-limited" in brief_text or "unavailable" in brief_text.lower():
            brief_text = "Environmental insights temporarily unavailable."
        return RiskBriefResponse(brief=brief_text)
    except Exception as e:
        logger.warning("risk-brief error: %s", e)
        return RiskBriefResponse(brief="Environmental insights temporarily unavailable.")
